In [466]:
import os
import cv2
import pandas as pd
%matplotlib inline
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from keras.utils import np_utils
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
import random
from keras.datasets import cifar10
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.optimizers import SGD, Adam
from keras.utils import np_utils
from sklearn.metrics import log_loss
from scipy.misc import imread, imresize
from keras.layers.convolutional import Convolution2D, MaxPooling2D
import keras
drivers=[]
images=[]
list_of_drivers=[]
list_of_image_names=[]
y_train=[]
x_train=[]
x_valid=[]
train_sample_size=5000
batch_size = 32
color_type=1
epochs = 200
data_augmentation = True

img_rows=img_cols=64

In [467]:
def return_drivers(go_path):
    train_path=os.path.join(go_path,'train/')
    drivers_file_names=os.listdir(train_path)
    for i in drivers_file_names:
        drivers.append(str(i))
    return drivers

In [468]:
def return_train_name_files(go_path,list_of_drivers):
    images=pd.read_csv(str(go_path)+'driver_imgs_list.csv')
    drivers_by_sort=images['classname']
    images_by_sort=images['img']
    return drivers_by_sort,images_by_sort

In [469]:
def main_call():
    y_valid=y_train=y_trainn=[]
    go_path="/home/beyhan/Kaggle/Araba_Pozisyon_Tahmin/imgs/"
    train_path="/home/beyhan/Kaggle/Araba_Pozisyon_Tahmin/imgs/train/"
    test_path="/home/beyhan/Kaggle/Araba_Pozisyon_Tahmin/imgs/train/"
    list_of_drivers=return_drivers(str(go_path))
    drivers,images=return_train_name_files(str(go_path),list_of_drivers)
    y_valid,y_train=read_train_image(drivers,images,train_path,wigth,height)
    x_test=read_test_image(test_path,wigth,height)
    y_valid,y_trainn=read_train_image(drivers,images,train_path,wigth,height,valid=True)
    #show_image(image1)
    return y_valid,y_train

In [513]:
x_test=[]

In [517]:
def read_test_image(test_path,wigth,height):
    arr = os.listdir(str(test_path))
    for i in arr:
        fill_test(str(test_path)+'/'+str(i),wigth,height)

In [518]:
def fill_test(image_path,wigth,height):
    img=cv2.imread(image_path,0)
    rotate = random.uniform(-10, 10)
    M = cv2.getRotationMatrix2D((img.shape[1]/2, img.shape[0]/2), rotate, 1)
    img = cv2.warpAffine(img, M, (img.shape[1], img.shape[0]))
    im = cv2.resize(img, (img_cols, img_rows), cv2.INTER_LINEAR)
    x_test.append(np.array(im, dtype=np.float32))


In [519]:
read_test_image('/home/beyhan/Kaggle/Araba_Pozisyon_Tahmin/imgs/test/',64,64)

In [470]:
def read_train_image(all_drivers,images,train_path,wigth,height,valid=False):
    y_valid=y_trainn=y_train=[]
    total=len(all_drivers)
    if valid==False:
        for index,val in enumerate(all_drivers):
            if index<total*8/10:
            #if index<50:
             im_path=str(train_path)+str(val)+'/'+str(images[index])
             fill_train(im_path,wigth,height)
        y_valid,y_train=fill_train_target(all_drivers)
    else:
        for index,val in enumerate(all_drivers):
            if index>=total*8/10:
            #if index<10:
             im_path=str(train_path)+str(val)+'/'+str(images[index])
             fill_train(im_path,wigth,height,valid=True)
        y_valid,y_trainn=fill_train_target(all_drivers,valid=True)

    return y_valid,y_train

In [471]:
def show_image(image_path):
    im=cv2.imread(image_path,0)
    plt.imshow(im)

In [472]:
def fill_train(image_path,wigth,height,valid=False):
    if valid==False:
        img=cv2.imread(image_path,0)
        rotate = random.uniform(-10, 10)
        M = cv2.getRotationMatrix2D((img.shape[1]/2, img.shape[0]/2), rotate, 1)
        img = cv2.warpAffine(img, M, (img.shape[1], img.shape[0]))
        im = cv2.resize(img, (img_cols, img_rows), cv2.INTER_LINEAR)
        x_train.append(np.array(im, dtype=np.float32))
    else:
        img=cv2.imread(image_path,0)
        rotate = random.uniform(-10, 10)
        M = cv2.getRotationMatrix2D((img.shape[1]/2, img.shape[0]/2), rotate, 1)
        img = cv2.warpAffine(img, M, (img.shape[1], img.shape[0]))
        im = cv2.resize(img, (img_cols, img_rows), cv2.INTER_LINEAR)
        x_valid.append(np.array(im, dtype=np.float32))
        print(np.shape(x_valid))

In [473]:
def fill_train_target(all_drivers,valid=False):
    y_valid=[]
    y_train=[]
    if valid==False:
        lb = LabelEncoder()
        y_train = lb.fit_transform(all_drivers)
        y_train = np.array(y_train, dtype=np.float32)
        y_train = cv2.resize(y_train, (10,np.shape(x_train)[0]), cv2.INTER_LINEAR)
    else:
        lb = LabelEncoder()
        y_valid = lb.fit_transform(all_drivers)
        y_valid = np.array(y_valid, dtype=np.float32)
        y_valid = cv2.resize(y_valid, (10,np.shape(x_valid)[0]), cv2.INTER_LINEAR)

    return y_valid,y_train

In [474]:
y_valid,y_train=main_call()


(1, 64, 64)
(2, 64, 64)
(3, 64, 64)
(4, 64, 64)
(5, 64, 64)
(6, 64, 64)
(7, 64, 64)
(8, 64, 64)
(9, 64, 64)
(10, 64, 64)
(11, 64, 64)
(12, 64, 64)
(13, 64, 64)
(14, 64, 64)
(15, 64, 64)
(16, 64, 64)
(17, 64, 64)
(18, 64, 64)
(19, 64, 64)
(20, 64, 64)
(21, 64, 64)
(22, 64, 64)
(23, 64, 64)
(24, 64, 64)
(25, 64, 64)
(26, 64, 64)
(27, 64, 64)
(28, 64, 64)
(29, 64, 64)
(30, 64, 64)
(31, 64, 64)
(32, 64, 64)
(33, 64, 64)
(34, 64, 64)
(35, 64, 64)
(36, 64, 64)
(37, 64, 64)
(38, 64, 64)
(39, 64, 64)
(40, 64, 64)
(41, 64, 64)
(42, 64, 64)
(43, 64, 64)
(44, 64, 64)
(45, 64, 64)
(46, 64, 64)
(47, 64, 64)
(48, 64, 64)
(49, 64, 64)
(50, 64, 64)
(51, 64, 64)
(52, 64, 64)
(53, 64, 64)
(54, 64, 64)
(55, 64, 64)
(56, 64, 64)
(57, 64, 64)
(58, 64, 64)
(59, 64, 64)
(60, 64, 64)
(61, 64, 64)
(62, 64, 64)
(63, 64, 64)
(64, 64, 64)
(65, 64, 64)
(66, 64, 64)
(67, 64, 64)
(68, 64, 64)
(69, 64, 64)
(70, 64, 64)
(71, 64, 64)
(72, 64, 64)
(73, 64, 64)
(74, 64, 64)
(75, 64, 64)
(76, 64, 64)
(77, 64, 64)
(78, 64,

(597, 64, 64)
(598, 64, 64)
(599, 64, 64)
(600, 64, 64)
(601, 64, 64)
(602, 64, 64)
(603, 64, 64)
(604, 64, 64)
(605, 64, 64)
(606, 64, 64)
(607, 64, 64)
(608, 64, 64)
(609, 64, 64)
(610, 64, 64)
(611, 64, 64)
(612, 64, 64)
(613, 64, 64)
(614, 64, 64)
(615, 64, 64)
(616, 64, 64)
(617, 64, 64)
(618, 64, 64)
(619, 64, 64)
(620, 64, 64)
(621, 64, 64)
(622, 64, 64)
(623, 64, 64)
(624, 64, 64)
(625, 64, 64)
(626, 64, 64)
(627, 64, 64)
(628, 64, 64)
(629, 64, 64)
(630, 64, 64)
(631, 64, 64)
(632, 64, 64)
(633, 64, 64)
(634, 64, 64)
(635, 64, 64)
(636, 64, 64)
(637, 64, 64)
(638, 64, 64)
(639, 64, 64)
(640, 64, 64)
(641, 64, 64)
(642, 64, 64)
(643, 64, 64)
(644, 64, 64)
(645, 64, 64)
(646, 64, 64)
(647, 64, 64)
(648, 64, 64)
(649, 64, 64)
(650, 64, 64)
(651, 64, 64)
(652, 64, 64)
(653, 64, 64)
(654, 64, 64)
(655, 64, 64)
(656, 64, 64)
(657, 64, 64)
(658, 64, 64)
(659, 64, 64)
(660, 64, 64)
(661, 64, 64)
(662, 64, 64)
(663, 64, 64)
(664, 64, 64)
(665, 64, 64)
(666, 64, 64)
(667, 64, 64)
(668, 

(1171, 64, 64)
(1172, 64, 64)
(1173, 64, 64)
(1174, 64, 64)
(1175, 64, 64)
(1176, 64, 64)
(1177, 64, 64)
(1178, 64, 64)
(1179, 64, 64)
(1180, 64, 64)
(1181, 64, 64)
(1182, 64, 64)
(1183, 64, 64)
(1184, 64, 64)
(1185, 64, 64)
(1186, 64, 64)
(1187, 64, 64)
(1188, 64, 64)
(1189, 64, 64)
(1190, 64, 64)
(1191, 64, 64)
(1192, 64, 64)
(1193, 64, 64)
(1194, 64, 64)
(1195, 64, 64)
(1196, 64, 64)
(1197, 64, 64)
(1198, 64, 64)
(1199, 64, 64)
(1200, 64, 64)
(1201, 64, 64)
(1202, 64, 64)
(1203, 64, 64)
(1204, 64, 64)
(1205, 64, 64)
(1206, 64, 64)
(1207, 64, 64)
(1208, 64, 64)
(1209, 64, 64)
(1210, 64, 64)
(1211, 64, 64)
(1212, 64, 64)
(1213, 64, 64)
(1214, 64, 64)
(1215, 64, 64)
(1216, 64, 64)
(1217, 64, 64)
(1218, 64, 64)
(1219, 64, 64)
(1220, 64, 64)
(1221, 64, 64)
(1222, 64, 64)
(1223, 64, 64)
(1224, 64, 64)
(1225, 64, 64)
(1226, 64, 64)
(1227, 64, 64)
(1228, 64, 64)
(1229, 64, 64)
(1230, 64, 64)
(1231, 64, 64)
(1232, 64, 64)
(1233, 64, 64)
(1234, 64, 64)
(1235, 64, 64)
(1236, 64, 64)
(1237, 64,

(1727, 64, 64)
(1728, 64, 64)
(1729, 64, 64)
(1730, 64, 64)
(1731, 64, 64)
(1732, 64, 64)
(1733, 64, 64)
(1734, 64, 64)
(1735, 64, 64)
(1736, 64, 64)
(1737, 64, 64)
(1738, 64, 64)
(1739, 64, 64)
(1740, 64, 64)
(1741, 64, 64)
(1742, 64, 64)
(1743, 64, 64)
(1744, 64, 64)
(1745, 64, 64)
(1746, 64, 64)
(1747, 64, 64)
(1748, 64, 64)
(1749, 64, 64)
(1750, 64, 64)
(1751, 64, 64)
(1752, 64, 64)
(1753, 64, 64)
(1754, 64, 64)
(1755, 64, 64)
(1756, 64, 64)
(1757, 64, 64)
(1758, 64, 64)
(1759, 64, 64)
(1760, 64, 64)
(1761, 64, 64)
(1762, 64, 64)
(1763, 64, 64)
(1764, 64, 64)
(1765, 64, 64)
(1766, 64, 64)
(1767, 64, 64)
(1768, 64, 64)
(1769, 64, 64)
(1770, 64, 64)
(1771, 64, 64)
(1772, 64, 64)
(1773, 64, 64)
(1774, 64, 64)
(1775, 64, 64)
(1776, 64, 64)
(1777, 64, 64)
(1778, 64, 64)
(1779, 64, 64)
(1780, 64, 64)
(1781, 64, 64)
(1782, 64, 64)
(1783, 64, 64)
(1784, 64, 64)
(1785, 64, 64)
(1786, 64, 64)
(1787, 64, 64)
(1788, 64, 64)
(1789, 64, 64)
(1790, 64, 64)
(1791, 64, 64)
(1792, 64, 64)
(1793, 64,

(2280, 64, 64)
(2281, 64, 64)
(2282, 64, 64)
(2283, 64, 64)
(2284, 64, 64)
(2285, 64, 64)
(2286, 64, 64)
(2287, 64, 64)
(2288, 64, 64)
(2289, 64, 64)
(2290, 64, 64)
(2291, 64, 64)
(2292, 64, 64)
(2293, 64, 64)
(2294, 64, 64)
(2295, 64, 64)
(2296, 64, 64)
(2297, 64, 64)
(2298, 64, 64)
(2299, 64, 64)
(2300, 64, 64)
(2301, 64, 64)
(2302, 64, 64)
(2303, 64, 64)
(2304, 64, 64)
(2305, 64, 64)
(2306, 64, 64)
(2307, 64, 64)
(2308, 64, 64)
(2309, 64, 64)
(2310, 64, 64)
(2311, 64, 64)
(2312, 64, 64)
(2313, 64, 64)
(2314, 64, 64)
(2315, 64, 64)
(2316, 64, 64)
(2317, 64, 64)
(2318, 64, 64)
(2319, 64, 64)
(2320, 64, 64)
(2321, 64, 64)
(2322, 64, 64)
(2323, 64, 64)
(2324, 64, 64)
(2325, 64, 64)
(2326, 64, 64)
(2327, 64, 64)
(2328, 64, 64)
(2329, 64, 64)
(2330, 64, 64)
(2331, 64, 64)
(2332, 64, 64)
(2333, 64, 64)
(2334, 64, 64)
(2335, 64, 64)
(2336, 64, 64)
(2337, 64, 64)
(2338, 64, 64)
(2339, 64, 64)
(2340, 64, 64)
(2341, 64, 64)
(2342, 64, 64)
(2343, 64, 64)
(2344, 64, 64)
(2345, 64, 64)
(2346, 64,

(2830, 64, 64)
(2831, 64, 64)
(2832, 64, 64)
(2833, 64, 64)
(2834, 64, 64)
(2835, 64, 64)
(2836, 64, 64)
(2837, 64, 64)
(2838, 64, 64)
(2839, 64, 64)
(2840, 64, 64)
(2841, 64, 64)
(2842, 64, 64)
(2843, 64, 64)
(2844, 64, 64)
(2845, 64, 64)
(2846, 64, 64)
(2847, 64, 64)
(2848, 64, 64)
(2849, 64, 64)
(2850, 64, 64)
(2851, 64, 64)
(2852, 64, 64)
(2853, 64, 64)
(2854, 64, 64)
(2855, 64, 64)
(2856, 64, 64)
(2857, 64, 64)
(2858, 64, 64)
(2859, 64, 64)
(2860, 64, 64)
(2861, 64, 64)
(2862, 64, 64)
(2863, 64, 64)
(2864, 64, 64)
(2865, 64, 64)
(2866, 64, 64)
(2867, 64, 64)
(2868, 64, 64)
(2869, 64, 64)
(2870, 64, 64)
(2871, 64, 64)
(2872, 64, 64)
(2873, 64, 64)
(2874, 64, 64)
(2875, 64, 64)
(2876, 64, 64)
(2877, 64, 64)
(2878, 64, 64)
(2879, 64, 64)
(2880, 64, 64)
(2881, 64, 64)
(2882, 64, 64)
(2883, 64, 64)
(2884, 64, 64)
(2885, 64, 64)
(2886, 64, 64)
(2887, 64, 64)
(2888, 64, 64)
(2889, 64, 64)
(2890, 64, 64)
(2891, 64, 64)
(2892, 64, 64)
(2893, 64, 64)
(2894, 64, 64)
(2895, 64, 64)
(2896, 64,

(3383, 64, 64)
(3384, 64, 64)
(3385, 64, 64)
(3386, 64, 64)
(3387, 64, 64)
(3388, 64, 64)
(3389, 64, 64)
(3390, 64, 64)
(3391, 64, 64)
(3392, 64, 64)
(3393, 64, 64)
(3394, 64, 64)
(3395, 64, 64)
(3396, 64, 64)
(3397, 64, 64)
(3398, 64, 64)
(3399, 64, 64)
(3400, 64, 64)
(3401, 64, 64)
(3402, 64, 64)
(3403, 64, 64)
(3404, 64, 64)
(3405, 64, 64)
(3406, 64, 64)
(3407, 64, 64)
(3408, 64, 64)
(3409, 64, 64)
(3410, 64, 64)
(3411, 64, 64)
(3412, 64, 64)
(3413, 64, 64)
(3414, 64, 64)
(3415, 64, 64)
(3416, 64, 64)
(3417, 64, 64)
(3418, 64, 64)
(3419, 64, 64)
(3420, 64, 64)
(3421, 64, 64)
(3422, 64, 64)
(3423, 64, 64)
(3424, 64, 64)
(3425, 64, 64)
(3426, 64, 64)
(3427, 64, 64)
(3428, 64, 64)
(3429, 64, 64)
(3430, 64, 64)
(3431, 64, 64)
(3432, 64, 64)
(3433, 64, 64)
(3434, 64, 64)
(3435, 64, 64)
(3436, 64, 64)
(3437, 64, 64)
(3438, 64, 64)
(3439, 64, 64)
(3440, 64, 64)
(3441, 64, 64)
(3442, 64, 64)
(3443, 64, 64)
(3444, 64, 64)
(3445, 64, 64)
(3446, 64, 64)
(3447, 64, 64)
(3448, 64, 64)
(3449, 64,

(3933, 64, 64)
(3934, 64, 64)
(3935, 64, 64)
(3936, 64, 64)
(3937, 64, 64)
(3938, 64, 64)
(3939, 64, 64)
(3940, 64, 64)
(3941, 64, 64)
(3942, 64, 64)
(3943, 64, 64)
(3944, 64, 64)
(3945, 64, 64)
(3946, 64, 64)
(3947, 64, 64)
(3948, 64, 64)
(3949, 64, 64)
(3950, 64, 64)
(3951, 64, 64)
(3952, 64, 64)
(3953, 64, 64)
(3954, 64, 64)
(3955, 64, 64)
(3956, 64, 64)
(3957, 64, 64)
(3958, 64, 64)
(3959, 64, 64)
(3960, 64, 64)
(3961, 64, 64)
(3962, 64, 64)
(3963, 64, 64)
(3964, 64, 64)
(3965, 64, 64)
(3966, 64, 64)
(3967, 64, 64)
(3968, 64, 64)
(3969, 64, 64)
(3970, 64, 64)
(3971, 64, 64)
(3972, 64, 64)
(3973, 64, 64)
(3974, 64, 64)
(3975, 64, 64)
(3976, 64, 64)
(3977, 64, 64)
(3978, 64, 64)
(3979, 64, 64)
(3980, 64, 64)
(3981, 64, 64)
(3982, 64, 64)
(3983, 64, 64)
(3984, 64, 64)
(3985, 64, 64)
(3986, 64, 64)
(3987, 64, 64)
(3988, 64, 64)
(3989, 64, 64)
(3990, 64, 64)
(3991, 64, 64)
(3992, 64, 64)
(3993, 64, 64)
(3994, 64, 64)
(3995, 64, 64)
(3996, 64, 64)
(3997, 64, 64)
(3998, 64, 64)
(3999, 64,

(4484, 64, 64)
(4485, 64, 64)


In [452]:
#now we have x_train,y_train,x_valid,y_valid. that's good point!

In [475]:
x_train = np.array(x_train, dtype=np.uint8)
x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
x_train = x_train.astype('float32')
x_train /= 255

In [476]:
x_valid = np.array(x_valid, dtype=np.uint8)
x_valid = x_valid.reshape(x_valid.shape[0], 1, img_rows, img_cols)
x_valid = x_valid.astype('float32')
x_valid /= 255

In [478]:
y_train.reshape(1, 1,10,x_train.shape[0])
y_valid.reshape(1, 1,10,x_valid.shape[0])


array([[[[ 0.,  0.,  0., ...,  6.,  6.,  6.],
         [ 6.,  6.,  6., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  9.,  9.,  9.],
         ..., 
         [ 3.,  3.,  3., ...,  1.,  1.,  1.],
         [ 1.,  1.,  1., ...,  7.,  7.,  7.],
         [ 7.,  7.,  7., ...,  9.,  9.,  9.]]]], dtype=float32)

In [494]:
for i in y_valid:
    print(i)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  

[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.94299316  5.94299316  5.94299316  5.94299316  5.94299316  5.94299316
  5.94299316  5.94299316  5.94299316  5.94299316]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.93969727  6.93969727  6.93969727  6.93969727  6.93969727  6.93969727
  6.93969727  6.93969727  6.93969727  6.93969727]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.

[ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
[ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
[ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
[ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
[ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
[ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
[ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
[ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
[ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
[ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
[ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
[ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
[ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
[ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  

[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  

[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  

[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  

[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  

[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.51464844  1.51464844  1.51464844  1.51464844  1.51464844  1.51464844
  1.51464844  1.51464844  1.51464844  1.51464844]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2. 

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
[ 3.  3.  3.  3.  3.  3.  3.  3.  

[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.34667969  0.34667969  0.34667969  0.34667969  0.34667969  0.34667969
  0.34667969  0.34667969  0.34667969  0.34667969]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1. 

[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
[ 8.27929688  8.27929688  8.27929688  8.27929688  8.27929688  8.27929688
  8.27929688  8.27929688  8.27929688  8.27929688]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
[ 9.  9.  9.  9.  9.  9.  9.  9.  9. 

[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
[ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
[ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
[ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
[ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
[ 3.  3.  3.  3.  3.  3.  3.  3.  

[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  

[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
[ 7.  7.  7.  7.  7.  7.  7.  7.  

In [479]:
#y_train = y_train.reshape((-1, 1))

In [480]:
#y_valid = y_valid.reshape((-1, 1))

In [508]:
def create_model():
    model = Sequential()
    model.add(Convolution2D(64, 3, 3, border_mode='same'
                            input_shape=(color_type, img_rows, img_cols)))
    model.add(MaxPooling2D(pool_size=(2, 2), dim_ordering="th"))
    model.add(Dropout(0.5))

    model.add(Convolution2D(128, 3, 3, border_mode='same'))
    model.add(MaxPooling2D(pool_size=(2, 2), dim_ordering="th"))

    model.add(Convolution2D(256, 3, 3, border_mode='same'))
    model.add(MaxPooling2D(pool_size=(2, 2), dim_ordering="th"))
    model.add(Dropout(0.5))

    model.add(Flatten())
    model.add(Dense(10))
    model.add(Activation('softmax'))

    return model

In [509]:
model=create_model()   

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:4: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), padding="same", kernel_initializer="he_normal", input_shape=(1, 64, 64...)`
  after removing the cwd from sys.path.
/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:5: UserWarning: Update your `MaxPooling2D` call to the Keras 2 API: `MaxPooling2D(data_format="channels_first", pool_size=(2, 2))`
  """
/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:8: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), padding="same", kernel_initializer="he_normal")`
  
/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:9: UserWarning: Update your `MaxPooling2D` call to the Keras 2 API: `MaxPooling2D(data_format="channels_first", pool_size=(2, 2))`
  if __name__ == '__main__':
/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:12: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Co

In [510]:
model.compile(optimizer='rmsprop',
          Adam(lr=0.01), loss='categorical_crossentropy',
          metrics=['accuracy'])

In [511]:
model.fit(x_train, y_train, batch_size=64, nb_epoch=epochs,
               verbose=1, validation_data=(x_valid,y_valid))


Train on 17939 samples, validate on 4485 samples
Epoch 1/200
17939/17939 [==============================] - 13s - loss: 100.0062 - acc: 0.1074 - val_loss: 99.9629 - val_acc: 0.5775
Epoch 2/200
17939/17939 [==============================] - 12s - loss: 99.8137 - acc: 0.1187 - val_loss: 99.9627 - val_acc: 0.3445
Epoch 3/200
17939/17939 [==============================] - 12s - loss: 99.8137 - acc: 0.1103 - val_loss: 99.9627 - val_acc: 0.5579
Epoch 4/200
17939/17939 [==============================] - 12s - loss: 99.8137 - acc: 0.1357 - val_loss: 99.9627 - val_acc: 0.0000e+00
Epoch 5/200
17939/17939 [==============================] - 12s - loss: 99.8137 - acc: 0.1775 - val_loss: 99.9627 - val_acc: 0.0000e+00
Epoch 6/200
17939/17939 [==============================] - 12s - loss: 99.8136 - acc: 0.2612 - val_loss: 99.9627 - val_acc: 0.0899
Epoch 7/200
17939/17939 [==============================] - 12s - loss: 99.8136 - acc: 0.2303 - val_loss: 99.9627 - val_acc: 0.0000e+00
Epoch 8/200
17939/179

17939/17939 [==============================] - 12s - loss: 99.8136 - acc: 0.3156 - val_loss: 99.9627 - val_acc: 0.0994
Epoch 63/200
17939/17939 [==============================] - 12s - loss: 99.8136 - acc: 0.2794 - val_loss: 99.9627 - val_acc: 0.0000e+00
Epoch 64/200
17939/17939 [==============================] - 12s - loss: 99.8136 - acc: 0.2466 - val_loss: 99.9627 - val_acc: 0.9960
Epoch 65/200
17939/17939 [==============================] - 12s - loss: 99.8136 - acc: 0.3027 - val_loss: 99.9627 - val_acc: 1.0000
Epoch 66/200
17939/17939 [==============================] - 12s - loss: 99.8136 - acc: 0.2621 - val_loss: 99.9627 - val_acc: 0.0000e+00
Epoch 67/200
17939/17939 [==============================] - 12s - loss: 99.8136 - acc: 0.3054 - val_loss: 99.9627 - val_acc: 0.0000e+00
Epoch 68/200
17939/17939 [==============================] - 12s - loss: 99.8136 - acc: 0.2708 - val_loss: 99.9627 - val_acc: 0.9915
Epoch 69/200
17939/17939 [==============================] - 12s - loss: 99.81

17939/17939 [==============================] - 12s - loss: 99.8136 - acc: 0.2498 - val_loss: 99.9627 - val_acc: 0.0000e+00
Epoch 183/200
17939/17939 [==============================] - 12s - loss: 99.8136 - acc: 0.3001 - val_loss: 99.9627 - val_acc: 1.0000
Epoch 184/200
17939/17939 [==============================] - 12s - loss: 99.8136 - acc: 0.2320 - val_loss: 99.9627 - val_acc: 0.9871
Epoch 185/200
17939/17939 [==============================] - 12s - loss: 99.8136 - acc: 0.1230 - val_loss: 99.9627 - val_acc: 0.0256
Epoch 186/200
17939/17939 [==============================] - 12s - loss: 99.8136 - acc: 0.1718 - val_loss: 99.9627 - val_acc: 0.2334
Epoch 187/200
17939/17939 [==============================] - 12s - loss: 99.8136 - acc: 0.2239 - val_loss: 99.9627 - val_acc: 0.0000e+00
Epoch 188/200
17939/17939 [==============================] - 12s - loss: 99.8137 - acc: 0.2330 - val_loss: 99.9627 - val_acc: 0.0000e+00
Epoch 189/200
17939/17939 [==============================] - 12s - loss